config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  resources :books
  
  get 'books/:id' => 'books#show',as:'show'
  get 'books/:id/edit' => 'books#edit',as:'edit'
  patch 'books/:id' => 'books#update', as: 'update'
  delete 'books/:id' => 'books#destroy', as: 'destroy'
  
  root :to => 'homes#top'
  get 'homes/top'
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    validates :title, presence: true
    validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   
    def new
    @book = Book.new 
    end
  
    def index
        @books = Book.all
    end
    
    def create
        book = Book.new(book_params)
        if @book.save
            flash[:notice] = "sBook was successfully created." 
            redirect_to show_path(book.id)
        else
            render :new
        end  
    end
    
    def show
        @book = Book.find(params[:id])
    end
  
    def edit
        @book = Book.find(params[:id])
    end
    
    def update
        book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "Book was successfully updated." 
            redirect_to show_path(book.id)  
        else
            render :new
        end
    end

    def destroy
        book = Book.find(params[:id])  
        book.destroy  
        redirect_to '/books' 
    end
    
  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="style.css" />
    <title>Bookers</title>
  </head>


<% if flash[:notice] %>
    <div class="flash">
         <%= flash[:notice] %>
    </div>
<% end %>
  <body>
    
    <h2>Editing Book</h2>
   
    <%= form_with model: @book, url: update_path(@book.id), method: :patch do |f| %>

      <ladel>Title</ladel>
      <%= f.text_field :title %>
      
      <ladel>Boby</ladel>
      <%= f.text_area :body %><br>
      
      <%= f.submit 'Update Books' %>
      
    <% end %>
    
    <p><%= link_to 'Show', show_path(@book.id) %></p>
    <p><a href="/books">Back</a></p>
  </body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Bookers</title>
  </head>

  <body>
    
    <h1>Bookers</h1>
    
    
    <table>
        <theadr>
        <tr>
        <th>Title</th>
        <th>Boby</th>
        <th colspan="3"></th>
        <tr>
        </theadr>
        
        <tboby>
        <%= @books.each do |book| %>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            <td><%= link_to 'Show', show_path(book.id) %></td>
            <td><%= link_to 'Edit', edit_path(book.id) %></a></td>
            <td><%= link_to "Destroy", destroy_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
        </tboby>
    </table>
    <% end %>
    
    
    
    <h2>New Books</h2>


    <%= form_with model: Book.new do |f| %>

      <ladel>Title</ladel>
      <%= f.text_field :title %>
      
      <ladel>Boby</ladel>
      <%= f.text_area :body %><br>
      
      <%= f.submit 'Create Books' %>
      
    <% end %>
  </body>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="style.css" />
    <title>Bookers</title>
  </head>

  <body>
    
    <p><strong>Title</strong><%= @book.title %></p>
    <p><strong>Boby</strong><%= @book.body %></p>
    
    <p><%= link_to 'Edit', edit_path(@book.id) %></p>
    <p><a href="/books">Back</a></p>
  </body>
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="style.css" />
    <title>Bookers</title>
  </head>

  <body>
    
    <h1>ようこそ　Bookersへ！</h1>
    <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
    <p><a href="/books">start</a></p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>